### ISSUE TITLE
nodename nor servname provided, or not known while running on Mac

### ISSUE THREAD

**Issue by griddic** [skillpub/collaboration#2]
```
skillpub                 
2020-10-29 14:06:01,384 - START
2020-10-29 14:06:01,393 - skills : hello
2020-10-29 14:06:01,567 - start Jupyter Lab
2020-10-29 14:06:03,006 - slack client initialized
2020-10-29 14:06:03,012 - slack channel started
2020-10-29 14:06:03,015 - start slack actions web service on http://0.0.0.0:5000
 * Serving Flask app "skillpub.bot" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-10-29 14:06:08,022 - [Errno 8] nodename nor servname provided, or not known
2020-10-29 14:06:08,023 - Traceback (most recent call last):
  File "skillpub/manager.py", line 909, in skillpub.manager.main
  File "skillpub/manager.py", line 196, in skillpub.manager.main_loop
  File "skillpub/api.py", line 29, in skillpub.api.Api.__init__
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

The workaround is to associate output from `python -c 'import socket; print(socket.gethostname())'` with `127.0.0.1` in `/etc/hosts`.

**Comment by skillpub** [comment]
Hi! Fixed in latest version ([0.2.86](https://pypi.org/project/skillpub/0.2.86/)).
Thank you and pls let me know whether it's solved.

**Comment by griddic** [comment]
Thanks! The problem is solved.
